version: '3'

# this file is just a reference for docker-composer... adjust paths and select services as needed

services:
  mysqldb:
    image:  mysql:latest
    # restart: always
    ports:
      - "33060:3306"
    volumes:
    - ../db_data:/app/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=ZanomaDashboardBrasil
      - MYSQL_USER=zanomabr
      - MYSQL_PASSWORD=zanomabr
  laravel:
    image: rafapaulin/laravel-dev:latest
    depends_on:
      - mysqldb
    links:
      - mysqldb:mysqldb
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
  nginx:
    image: rafapaulin/nginx-dev:latest
    depends_on:
      - laravel
    links:
      - laravel:fpm
    environment:
      - NGINX_SERVER_NAME=localhost
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    command: /bin/sh -c "envsubst '$$NGINX_SERVER_NAME $$FPM_NAME' < /etc/nginx/conf.d/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  apache:
    image: rafapaulin/apache-dev:latest
    ports:
      - "8000:80"
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/